### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by MikeDMorgan** [MarioniLab/miloDE#19]
Be explicit about function imports - setdiff isn't defined anywhere (also, why not just use the `base::diff`?):
https://github.com/MarioniLab/miloDE/blob/d763aa0fa6c11cbf17eb08c108c6dfe18b51b168/R/de_test_all_hoods.R#L59

Don't use `F` and `T` as these can easily be overwritten by users, use `TRUE` and `FALSE` explicitly:
https://github.com/MarioniLab/miloDE/blob/d763aa0fa6c11cbf17eb08c108c6dfe18b51b168/R/de_test_all_hoods.R#L63
https://github.com/MarioniLab/miloDE/blob/d763aa0fa6c11cbf17eb08c108c6dfe18b51b168/R/de_test_all_hoods.R#L99
https://github.com/MarioniLab/miloDE/blob/d763aa0fa6c11cbf17eb08c108c6dfe18b51b168/R/de_test_all_hoods.R#L106

You can define the output order of `topTags`, it doesn't need to be done here, or set `topTags(..., sort.by='none')`: 
https://www.rdocumentation.org/packages/edgeR/versions/3.14.0/topics/topTags
https://github.com/MarioniLab/miloDE/blob/d763aa0fa6c11cbf17eb08c108c6dfe18b51b168/R/de_test_all_hoods.R#L254

**Comment by amissarova** [comment]
done
