### ISSUE TITLE
Rendering vignette to view from README

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloDE#20]
Instead of linking to a dropbox folder, you can store the rendered version in HTML somewhere in the repo (you can build it manually with `kritr` or make a `docs` folder using something like [pkgdown](https://github.com/r-lib/pkgdown)) and you can make a rendered link using https://raw.githack.com/ 

Example from miloR:
- Original link: https://github.com/MarioniLab/miloR/blob/master/docs/articles/milo_gastrulation.html
- Rendered with raw.githack: https://rawcdn.githack.com/MarioniLab/miloR/bcc9e785442ff8bafe7c507f2d8392851e89339c/docs/articles/milo_gastrulation.html

**Comment by amissarova** [comment]
yeah i was gonna do it closer to the submission - will leave an issue open tho so wont forget

**Comment by amissarova** [comment]
done
