### ISSUE TITLE
Augur dependency

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloDE#21]
At the moment `Augur` is a dependency
https://github.com/MarioniLab/miloDE/blob/13ec4fa6320b9fd2ff681b6019af787d6d58011e/NAMESPACE#L17

but the README says you have to install it yourself. 

Does it need to be a dependency?

**Comment by amissarova** [comment]
that's a bug, here should be scWGCNA package - I'll fix

**Comment by amissarova** [comment]
fixed

**Comment by pranithavangala** [comment]
Did you fix this ? I still see augur @amissarova
