### ISSUE TITLE
edge_width cannot be changed in plot_milo_by_single_metric

### ISSUE THREAD

**Issue by mihem** [MarioniLab/miloDE#32]
Just a small bug here:

https://github.com/MarioniLab/miloDE/blob/8803302dd67c371b638340c10d09a2dea6eb8152/R/plotting_functions.R#L181

I think it should be 
```
scale_edge_width(range = edge_width)
```

At least in my case chaning edge_width does not do anything. A workarround is overwriting this parameter via

```
plot_milo_by_single_metric(milo_obj ....) +
  ggraph::scale_edge_width(range = c(0.01, 0.1))
```

**Comment by amissarova** [comment]
@mihem thanks for pointing this out, its fixed now
